package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        step {
            type = "cargo"
            param("cargo-command", "build")
        }
        step {
            type = "cargo"
            param("cargo-command", "test")
        }
    }
    steps {
        insert(0) {
            dockerCommand {
                name = "Build container image"
                commandType = build {
                    source = path {
                        path = "Dockerfile"
                    }
                    commandArgs = "--pull"
                }
                param("dockerImage.platform", "linux")
            }
        }
        items.removeAt(1)
        items.removeAt(1)
    }
}
